use_frameworks!

target 'TextFieldFloatingPlaceholder_Example' do
  pod 'TextFieldFloatingPlaceholder', :path => '../'

  target 'TextFieldFloatingPlaceholder_Tests' do
    inherit! :search_paths

    
  end
end
